# Generated by Django 5.0.4 on 2024-05-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='totalamount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
