# Generated by Django 5.0.4 on 2024-05-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_payment_totalamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
